version: '3'

vars:
  SHELL_RC:
    sh: |
      if [[ -f "${HOME}/.zshrc" && "$SHELL" == *"zsh"* ]]; then
        echo "${HOME}/.zshrc"
      else
        echo "${HOME}/.bashrc"
      fi

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Install project dependencies with uv
    cmds:
      - uv pip install -e .
    sources:
      - pyproject.toml

  sync:
    desc: Sync dependencies from lock file
    cmds:
      - uv sync

  lock:
    desc: Update the lock file
    cmds:
      - uv lock

  venv:
    desc: Create virtual environment with uv
    cmds:
      - uv venv
    status:
      - test -d .venv

  setup:env:
    desc: Create .env file from template
    cmds:
      - cp .env.template .env
      - |
        echo "Created .env file. Please edit it with your settings:"
        echo "  - ANTHROPIC_API_KEY: Your Anthropic API key"
        echo "  - USB_DIR or Google Drive settings for notes source"
        echo "  - ANALYSIS_OUTPUT_DIR for saving analysis files (required for Google Drive)"
    status:
      - test -f .env

  setup:output-dir:
    desc: Create the analysis output directory from .env configuration
    cmds:
      - |
        if [ -f .env ]; then
          OUTPUT_DIR=$(grep -E "^ANALYSIS_OUTPUT_DIR=" .env | cut -d'=' -f2- | tr -d '"' | tr -d "'")
          if [ -n "$OUTPUT_DIR" ]; then
            mkdir -p "$OUTPUT_DIR/daily" "$OUTPUT_DIR/weekly"
            echo "Created output directories:"
            echo "  $OUTPUT_DIR/daily/"
            echo "  $OUTPUT_DIR/weekly/"
          else
            echo "ANALYSIS_OUTPUT_DIR not set in .env - skipping directory creation"
          fi
        else
          echo "No .env file found. Run 'task setup:env' first."
        fi

  setup:
    desc: Full first-time setup (venv, install, env file)
    cmds:
      - task: venv
      - task: install
      - task: setup:env
      - |
        echo ""
        echo "Setup complete! Next steps:"
        echo "  1. Edit .env with your API key and notes source configuration"
        echo "  2. Run 'source .venv/bin/activate' to activate the virtual environment"
        echo "  3. Run 'task setup:output-dir' to create the analysis output directory"
        echo "  4. Run 'task aliases' to add shell shortcuts (optional)"

  test:
    desc: Run tests
    deps: [install]
    cmds:
      - uv run pytest -v

  aliases:
    desc: Add daily/weekly alias commands to shell config
    preconditions:
      - sh: 'grep -q "# TaskTriage aliases" "{{.SHELL_RC}}" 2>/dev/null && exit 1 || exit 0'
        msg: "Aliases already exist in {{.SHELL_RC}}. Run 'task aliases:remove' first to update."
    cmds:
      - echo "" >> "{{.SHELL_RC}}"
      - echo "# TaskTriage aliases" >> "{{.SHELL_RC}}"
      - echo "alias daily='task-triage --type daily'" >> "{{.SHELL_RC}}"
      - echo "alias weekly='task-triage --type weekly'" >> "{{.SHELL_RC}}"
      - echo "Aliases added to {{.SHELL_RC}}"
      - echo "Run 'source {{.SHELL_RC}}' or restart your terminal to use them."

  aliases:remove:
    desc: Remove aliases from shell config
    cmds:
      - sed -i '/# TaskTriage aliases/,/^alias weekly=/d' "{{.SHELL_RC}}"
      - echo "Aliases removed from {{.SHELL_RC}}"

  clean:
    desc: Remove build artifacts and cache files
    cmds:
      - rm -rf build/ dist/ *.egg-info/ .pytest_cache/
      - find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
      - find . -type f -name "*.pyc" -delete 2>/dev/null || true

  clean:all:
    desc: Remove all generated files including venv
    deps: [clean]
    cmds:
      - rm -rf .venv/ uv.lock
